### ISSUE TITLE
看牌功能

### ISSUE THREAD

**Issue by Terrible-creeper** [KageRyo/Concentration#13]
如果在看牌的時候一直點其中一張卡片
在翻牌回來後我一直點的卡片無論如何點都不會翻牌(被認定為已翻牌狀態)

再點擊別張卡片 讓紀錄系統跑一次判斷 即可恢復

**Comment by KageRyo** [comment]
感謝回報，我們將會在下一個版本修復它（如果有下一個版本）。

**Comment by KageRyo** [comment]
Fix with new version.
