### ISSUE TITLE
整理檔案結構

### ISSUE THREAD

**Issue by KageRyo** [KageRyo/Concentration#16]
將字型改放為 `fonts` 資料夾
將JavaScript與CSS檔改放於 `assets` 資料夾

- Concentration
- - LICENSE
- - README.md
- - index.html
- - fonts
- - - Cubic.ttf
- - assets
- - - script.js
- - - LocaleSwitch.js
- - - jquery-3.6.1.js
- - - locale.js
- - - style.css

**Comment by RRAaru** [comment]
已經完成
